name: A1Wiki-sync
on:
  schedule:
    - cron: '4 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lan-tianxiang-JS_TOOL
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lan-tianxiang-JS_TOOL
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lan-tianxiang/JS_TOOL.wiki.git"
          source_branch: "A1"
          destination_branch: "A1Wiki"
          github_token: ${{ secrets.PAT }}

