name: v3-sync
on:
  schedule:
    - cron: '5 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-wudongdefeng-jd-base
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync wudongdefeng-jd-base
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wudongdefeng/jd-base.git"
          source_branch: "v3"
          destination_branch: "v3"
          github_token: ${{ secrets.PAT }}
