name: YG-tsj_EUserv-warp-sync
on:
  schedule:
    - cron: '7 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-YG-tsj-EUserv-warp
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync YG-tsj-EUserv-warp
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/YG-tsj/EUserv-warp.git"
          source_branch: "main"
          destination_branch: "YG-tsj_EUserv-warp"
          github_token: ${{ secrets.PAT }}
